### ISSUE TITLE
Writing in files (save and restore)

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#11]
The Vorple doc says these work erratically; in my experience, they don't work at all...

More generally, it would be interesting to make writing in files easier; this would mean extensions who implement achievements could potentially work and provide achievements persistence (provided a user doesn't delete the browser files or cookies that encode this).

**Comment by juhana** [comment]
This should get fixed after Parchment has been updated to the newest version.

**Comment by juhana** [comment]
Works in version 3.
