### ISSUE TITLE
Output abruptly stops

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#13]
This may be an VorpleI6 bug, but I don't really know how to diagnose this...

Sometimes, the game does not print the whole text, and just goes back to the prompt. This happens in some rather unpredictable cases, but a common denominator is a routine calling a routine.

I'll work on getting a minimal example to (not) work, or I could just show you an example of a game which doesn't work.

**Comment by hlabrand** [comment]
[issue-13.zip](https://github.com/juhana/vorple/files/362697/issue-13.zip)

Here's a minimal example, with makefile, and additional information.

In I6, custom responses to actions go in the "before" property of an object :
"Object monster
with before [; Attack: "You hit."; ];"
The return value can be : false (in which case the action 'carries on' and the default message is printed), true (end of the action and of the turn), or a string (the string is displayed and the value that's returned is true).

If the response has a hyperlink, everything is normal when true or false are returned; but if a string is returned, it is never displayed and is 'eaten', as well as the line break.
But if my "description" routine (describing the response to examine) has hyperlinks and returns a string, everything is fine. Same goes for a custom verb.

**Comment by juhana** [comment]
Probably not an issue in version 3.
