### ISSUE TITLE
Control duration of notification display individually (feature request)

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#14]
In the current system, the length of time for which notifications are displayed is always the same. One can change that value using
vorple.notify.defaults.timeout = 10000

Would it be possible to have a system in which one can give an optional argument which is the duration of that particular notification ? For some notifications (tutorials, etc), it is interesting to have them display for a long time.

**Comment by juhana** [comment]
You can set the notification duration with the JS library, but it would be good to be able to do so with the Inform extensions.

**Comment by juhana** [comment]
Now possible in version 3 extensions/libraries.
