### ISSUE TITLE
Displaying the prompt

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#18]
The I6 library has a "Prompt" message, defined in the LanguageLM/L__M routine of every language (English.h, French.h, etc.), and called at the beginning of every turn (in the Keyboard routine in parserm.h). This allows customization of the prompt, and for instance making it display "What do you want to do now? >" instead of just ">" ; it is even the recommended way to do this (exercise 59 page 191 of the DM4).

Vorple seems to ignore this routine (I think?), instead drawing its own vorplePrompt element. Vorple should execute that Prompt library message (L__M(##Prompt) in I6) and display this inside the element, instead of just displaying >. This would allow the customization of the prompt, including with hyperlinks. However, one should be careful to maintain compatibility with the "tooltip on the prompt" function defined in the tooltips file.

**Comment by juhana** [comment]
Prompt system redone in the latest version; new mechanism for changing the prompt.
