### ISSUE TITLE
Images: alt or title ?

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#23]
The Multimedia extension gives the possibility of adding a description to an image ; the description is printed in the non-Vorple interpreters, and put in an "alt" attribute in the HTML page generated by the Vorple interpreter.

I have found a few sources on the Internet saying that putting text in "alt" means the image is ignored by screen readers. It also depends on the browser, apparently, since the HTML spec is unclear. This kinds of defeat the purpose, doesn't it?
Apparently, using the "title" attribute is a better solution, as the title of an image will be read by a screen reader (as long as "alt" is empty)

Sources:
https://www.paciellogroup.com/blog/2016/02/short-note-on-use-of-alt-and-the-title-attribute/
https://www.powermapper.com/tests/screen-readers/labelling/img-title/

**Comment by hlabrand** [comment]
Oops sorry, this should go in the inform7 tracker...

**Comment by juhana** [comment]
As far as I can tell, the issue arises only when the image has an empty alt text and a title attribute, in which case the screen reader doesn't read the title. If that's the case then we're good: the extension doesn't try to add any screen reader specific text to the title so there's no conflict.
