### ISSUE TITLE
Sounds issues with Chrome

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#28]
Since now Chrome doesn't play sounds that start automatically, we should be sure that Vorple games are not affected.

Someone reported that some sounds do not work on [his game](http://www.fiction-interactive.fr/fi/corax/hansel-gretel/play.html). More specifically, the introduction music (immediatly after the game loads) does not play, but the rest seems to be unaffected. Everything is OK on Firefox and I haven't tested on other browsers.

**Comment by juhana** [comment]
The best solution I could come up with is that there should be a way to ensure the player interacts with the page by adding an optional title screen with a "play" button. That way any intro music and sounds play as a reaction to that button click.

**Comment by juhana** [comment]
The documentation now discusses this in detail, but there's not much else we can do about this. The Chrome model has spread to other browsers too and there's little chance that the situation will ever change (thanks advertisers!)
