### ISSUE TITLE
glk_gestalt(gestalt_Hyperlinks, 0) not working

### ISSUE THREAD

**Issue by jomali** [vorple/vorple#29]
If you use a `glk_set_hyperlink()`, the interpreter throws an exception, so I understand that the glk hyperlinks don't work in Vorple ---that's not necessarily a problem---. But, if I'm not wrong, you cannot use: `if (glk_gestalt(gestalt_Hyperlinks, 0)) glk_set_hyperlink(obj);` either; it passes the checking and tries to set an hyperlink ---and throws the corresponding exception---.

**Comment by jomali** [comment]
Ok! Excuse me for rising the issue, and thank you for the tips.

**Comment by curiousdannii** [comment]
Hmm, how does it pass the glk_gestalt check? There's nothing about hyperlinks in https://github.com/vorple/cheapglk/blob/master/cggestal.c

**Comment by juhana** [comment]
The new version doesn't break/crash on Glulx errors.
