### ISSUE TITLE
Error when executing JS that returns a cyclic object

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#32]
Consider the following;

```inform7
execute JavaScript command "var a = {}; a.b = a; var x = a";
```
When Vorple executes this JS, it tries to read the returned value. Since it is an object, `JSON.stringify` is called, which causes an error because the object is cyclic.

For context, the error happened while creating a new object defined in an external library (howler.js). I was executing something similar to this:

```javascript
// When play begins
var sounds = {};

// At some point in the story
sounds.mySound = new Howl(...)
```
Apparently, the Howl object is cyclic, and the error made it unusable for some reason. It took me a lot of time to find that the error came from Vorple, and not from my code or from the library.

**Comment by juhana** [comment]
That's a good catch! I'll fix it in the next release.

You probably fixed it already, but if someone else stumbles upon the same issue, the workaround is to add an expression at the end of the command that won't throw the error (e.g. `"myVar = circularObject; true;`)
