### ISSUE TITLE
Keep what the player has previously typed when queueing a command

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#36]
If the player starts typing something, but then the game queues a command, what the player had typed will be lost after the queued command is executed. The ability to keep the previous command could be a phrase option so that the author can choose.

This issue arose quite some time ago [when I was using timers](https://www.intfiction.org/forum/viewtopic.php?f=7&t=21984#p121062), and I thought maybe it could be something that Vorple automatically takes care of.

**Comment by juhana** [comment]
Fixed in 3.2.0
