### ISSUE TITLE
Git engine slower in 3.1 than in 3.0 preview

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#39]
I'm helping someone for a Vorple project. Recently, he updated it to 3.1 and noticed the game was really slower.

For example, after clicking on a in-game link, it would take more than 2 seconds to update the game when it took less than half a second before.

In a standard parser game, the difference is not really noticeable, but his game calls a lot of JavaScript after each command. (For example, executing multiple JS commands in a loop to construct an HTML table).

After investigating, I deduced it came from Git. So I replaced the `engine.js` and `engine.js.mem` files with the `git.js` and `git.js.mem` files from Vorple 3.0 preview (renaming them to "engine"). After that, the game was fast again. (I don't know if there can be side effect to this manipulation.)

If you can't reproduce this issue, I'll ask if I can send you the game in both versions (it's not public yet).

**Comment by juhana** [comment]
Thanks, I'll try that and see if it fixes the issue!

**Comment by curiousdannii** [comment]
It won't fix it all the way! The Emterpreter is just inherently slow, and unfortunately the way Git is designed there are some major functions which need to be Emterpreted. If you could use WASM that would help a little as well.

**Comment by juhana** [comment]
Switching to Quixe in 3.2.0 has improved evaluation time significantly.
