### ISSUE TITLE
Status line doesnt obscure everything on the right

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#40]
![petting](https://user-images.githubusercontent.com/1617462/60506454-26cdf400-9cc6-11e9-979b-1bc715a200ff.png)
![petting2](https://user-images.githubusercontent.com/1617462/60506455-27668a80-9cc6-11e9-9c65-76a62c2f7eee.png)

There is a problem with the status line CSS (see Petting Zoo screenshots).
vorple.css gives it a margin-left of -15px so the line encompasses the whole text; but the width of the status line in inherited (see a few lines before), and so it's as wide as the output. The status line is thus a little bit to the left, and any text displaying near the right side of the output is displayed right after the end of the status line eventually (after scrolling).

It's a good idea to have the status line a bit bigger than the output, but the width should be 30px bigger than the output for the effect to be correctly done; or just remove the negative margin.

**Comment by juhana** [comment]
Fixed in 3.2.0
