### ISSUE TITLE
Processing the story output before displaying it

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#41]
I'd like to know if it's possible to process the text output by the interpreter, just before it is added to the page. 

One use case, for example, would be to convert straight quotation marks to curly ones.

If there is no easy way yet, then it's a feature request. This is how I would maybe see it.

If a certain function is defined, then it is called just after the interpreter outputs some text, and just before this text is added to the page.

The function would take 2 arguments: a string containing the text, and the element object where the text will be displayed.

If the function returns `undefined`, then Vorple displays the text as usual. If the function returns a string, then this string is displayed instead. If an object like `{ el: myElement, text: myText }` is returned then the text given is displayed in the given element.

(The part where we can display the text in another element that the focused one is not mandatory, but it could be interesting?)

**Comment by juhana** [comment]
This is coming in the next release, along with capturing player input! Right now there isn't a good way to do that, unfortunately.

**Comment by juhana** [comment]
Available in 3.2.0 as input filters
