### ISSUE TITLE
"Using Vorple as a part of a JavaScript project" section in readme is outdated

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#44]
The section "Using Vorple as a part of a JavaScript project" seems outdated: it still mentions Git engine even if Vorple switched to Quixe.

Also, it would be good to have an explicit example of a project's structure. And as Vorple is published on NPM, it would be a good to explain how to use it with NPM instead of manually copying the `src` folder.

(In fact I just checked and the version of Vorple on NPM is not the latest. It should be updated.)

**Comment by juhana** [comment]
This is now finally fixed in 3.2.3: the source code is structured so that it can be better included in existing JS code, and the documentation has been moved to the web site: https://vorple-if.com/docs/js-library.html
