### ISSUE TITLE
Vorple Screen Effects records keypresses in Vex dialogs

### ISSUE THREAD

**Issue by chinkeeyong** [vorple/vorple#48]
When in a dialog like the one for saving your game, the Vorple prompt queues all keypresses that the player makes. This leads to undesirable behavior when you use Vorple Screen Effects's "wait for any key" feature.

**Reproducing the issue**
Make a story file with a few "wait for any key" prompts.
Open the story in the Vorple interpreter, open a Vex dialog (such as the one for saving your game), and type some things.
Return to the story and trigger the "wait for any key" prompts.

**Expected behavior**
The story waits for the next user keypress.

**Actual behavior**
The keypresses queued from the Vex dialog fire all at once without any user input.

**Comment by juhana** [comment]
Thanks, this will be fixed in the next release.
