### ISSUE TITLE
Cover art breaks Vorple's Quixe implementation

### ISSUE THREAD

**Issue by chinkeeyong** [vorple/vorple#49]
**Reproducing the issue**
Make a story file with cover art as described in Writing with Inform §25.8. Cover art.
Release with the Vorple interpreter.
Attempt to run the generated gblorb.js in Vorple.

**Expected behavior**
The story runs normally.

**Actual behavior**
Quixe crashes with an error message stating that the story file is not a valid Glulx file (because GlkOte is not defined).

**Comment by juhana** [comment]
This is now fixed in 3.2.6.
