### ISSUE TITLE
Importing JS Modules when including Vorple in React Project

### ISSUE THREAD

**Issue by Keeeeeeeks** [vorple/vorple#50]
Hey, working on integrating some stories into a React project, and I wasn't able to find a means to create a React component that, given a .ulx file that relies on external JS, is able to run commands within the story successfully. I was able to do it when releasing the story as its own standalone page, but figured that given the different dependencies I'm trying to use, putting the story in a React component might be easier. 

https://vorple-if.com/docs/js-library.html#react-project

Is there a param within the vorple.options object, or some other alternative for calling external JS files through a .ulx released story?

**Comment by juhana** [comment]
JS run from within Inform can only access things in the global window scope. So somewhere in the React project you need to do for example:

```javascript
import { something } from "someModule";

window.something = something;
```

Now you can access `something` when evaluating JS in Inform.

**Comment by Keeeeeeeks** [comment]
This makes sense, I was referring to the React file (in this case JSX file) where I'm using the vorple.options object to render the story in a component. I get that one can drop JS files into the released static web page directory and use the window scope method you mentioned above to access modules while in Inform, but how do I ensure that, when including Vorple in a React project (and not releasing in a static page), the JS needed in the story is able to be called? 

The goal here was, once I figured this out, I could use the modules I already had in the project, and basically standardize a lot of the work if multiple different stories relied on similar JS modules.

Snippet below

```import React, { useEffect, useRef } from 'react';
import vorple from "vorple";
import { Row } from "antd";
import { Address } from "../components";
import wikipedia_query from "../books/everything.js"
import "vorple/lib/css/vorple.css";


var storyFile1 = import("../books/3AW4.ulx");

window.jump = jump;
window.wikipedia_query = wikipedia_query;



export default function Vorple2( address, vorpAddress, userProvider, mainnetProvider, localProvider, storyFile) {
    const containerRef = useRef(null);
    const FS = vorple.file.getFS();
    window.storyFile = storyFile;
    var storyFile = "../books/3AW4.ulx";

    useEffect(() => {
        if( containerRef ) {
            vorple.options = {
                story: "../books/3AW4.ulx",

                container: containerRef.current
            };
            vorple.init();
        } 
    }, [ containerRef ]);


        return (
            <Row align="middle">
                    <vorple-section>
                        <div class="vorple-content">
                            <div class="vorple-box">
                                <section>                                    
                                    <div ref={containerRef} />
                                </section>
                            </div>
                        </div>
                        <div class="push">

                        </div>
                    </vorple-section>
            </Row>
        )


}

**Comment by juhana** [comment]
React shouldn't make any difference in that regard. I'm not quite sure where the issue is, but if you want more debugging help you can send me an email to juhana.if at nitku.net.

**Comment by Keeeeeeeks** [comment]
Update: It worked, just needed to follow your directions for all of the variables in the file.
