### ISSUE TITLE
URL for submodule causes issues when provided as SSH instead of HTTPS

### ISSUE THREAD

**Issue by weaversam8** [vorple/vorple#53]
Unrelated to #43. When attempting to clone this project, the fact that the repository URL for Haven was listed as an SSH URL instead of an HTTPS url prevented me from cloning submodules. I think this is because I usually use HTTPS and haven't configured my computer with keys to clone from SSH.

**Is there a reason SSH was chosen over HTTPS?** Changing the `.gitmodules` file to the below resolved the issue:

```diff
diff --git a/.gitmodules b/.gitmodules
index 1226d9d..f31586f 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,6 +1,6 @@
 [submodule "src/haven"]
        path = src/haven
-       url = git@github.com:vorple/haven.git
+       url = https://github.com/vorple/haven.git
 [submodule "quixe"]
        path = src/quixe
        url = https://github.com/erkyrath/quixe.git
```

(note: if you've already used `git submodules update --init` you may also need to update `.git/config` to contain the correct URL after updating `.gitmodules`)

**Comment by juhana** [comment]
No other reason than that Github offers the SSH version of the URI by default. I can change it to the HTTPS version if that's easier to people.
