### ISSUE TITLE
org:vorple place hyperlink before end the story

### ISSUE THREAD

**Issue by kdabwl** [vorple/vorple#55]
Hello,

there is a reproducible nasty bug when placing a link -and- in the next line ending the story.
You can see [Ctrl-F] the [source here](https://inform.goeppel.eu/source/The%20User's%20Programs%20(Tron-)%20in%20Cyberspace.ni), the problem appears when the line "place a link" runs in the After dropping part - just before end the story. The link is not seen by the user; but the same code has no problem when moved away from end the story.
You can start from [play.html here](https://t.me/swarmLinkBot) (hit the Inform7 button after starting the bot app) & for that use Telegram app (as Desktop app on Mac not so good, but the Android app and Win11 desktop app/s are running w/o problem).

P.S. recently came the [opportunity to integrate](https://core.telegram.org/bots/webapps) <script src="https://telegram.org/js/telegram-web-app.js"></script> in the play.html, how about accessing their [things in the DOM](https://core.telegram.org/bots/webapps#themeparams) interactively?

**Comment by juhana** [comment]
I've tested the code and it seems to work correctly. TEST ME ends with this:

> [8] throw that artefact
> [you are winning! claim your prize! with this win notification!](https://fb92565f55a9410b8939b94f42ea6228.ide-play.borogove.io/source/The%20User's%20Programs%20(Tron-)%20in%20Cyberspace.ni)
> 
> 
> *** now the artefact is dynamic front and center, you win ***

Demo here: https://snippets.borogove.app/inform7/z25gz5

Did I misunderstood what the problem is, or is it maybe something that happens only with Telegram?

**Comment by kdabwl** [comment]
@[juhana](https://github.com/juhana) your test was O.K. because the troubled line is moved away from the end the story finally saying.  Move the place a link to, downward to After dropping, then you can reproduce.
Didn't want to annoy users by promising a special prize but exactly that code line wouldn't work.
You have the source, give it a try.
And thanks for testing with borogove, looks great :-D

**Comment by juhana** [comment]
Sorry, I still can't reproduce even after moving the line to the After rule. It behaves the same as it did before. Could you show a version of the code that has the issue?

**Comment by kdabwl** [comment]
You are right. Now the line, where it made the trouble, works as designed. And no longer reproducible (took us quite some time to work around after trouble appeared).
We'll leave it as it is now (you may try updated stuff). Perhaps it was a css problem on our side. We'll observe and maybe report, ifF it appears again.

B.t.w. the .play browser page has a relolad button in Telegram app and that works (http logfile check). But the .ni source code browser page (in Telegram app) has no such thing. The only way we worked around was to clear the history of @swarmLinkBot and wait for the middleware to recognize (checked status with Telegram desktop app).

Anyways, Vorple output from Inform7 rules, and I thank you for the effort and publication.

**Comment by juhana** [comment]
Glad you got it working, feel free to re-open if it happens again.
