### ISSUE TITLE
placing tags before & after the banner text

### ISSUE THREAD

**Issue by kdabwl** [vorple/vorple#56]
Hello,
I refer to [§18.37. Printing the banner text](http://inform7.com/book/WI_18_37.html) where it says what is in the banner text.
In good old pre-Cascading Style Sheets times (and unchanged therafter) the way to make boring text smaller was to put `<sub><sup>`around it`</sup></sub>` which renders small but readable (and easy selectable) in the currently active font (etc).

With Vorple the end tags are placed Okay, After printing the banner text, but the opening tags come too late for text in the story description (same for Before printing the banner & When play begins). If there is a workaround please let me know.

**Comment by juhana** [comment]
It doesn't sound like a Vorple issue as such, so you might want to ask at the forums instead with more details about where you want to place the tags: https://intfiction.org/c/authoring/inform-7/19

**Comment by kdabwl** [comment]
Ah, the [responsibility blame game](https://gigablast.com/search?q=responsibility+blame+social) at work, we'll pass the message to donor and client.
