### ISSUE TITLE
How to import custom JavaScript files in Inform 7 with Vorple?

### ISSUE THREAD

**Issue by Baytars** [vorple/vorple#59]
In the documentation I saw that custom css files can be imported using the instruction `Release along with the style sheet "myCustomStyles.css".`, but I can't see how to import custom .js files in Inform 7 with Vorple.
Importing custom .js files in Inform 7 with Vorple can be important if I want to define some custom JavaScript functions for the convenience of calling these functions using the instruction `execute JavaScript command`.

**Comment by Baytars** [comment]
OK, I saw that this feature is indeed available from the example [The Sum of Human Knowledge](https://vorple-if.com/docs/extension-vorple.html#the-sum-of-human-knowledge), with the instruction `Release along with JavaScript "encyclopedia.js".`. I think this feature is worth a documentation topic, isn't it?

**Comment by juhana** [comment]
Good point, technically it's an Inform feature but I'll make sure to add a note about it in the docs.
