### ISSUE TITLE
Say followed by pause throws JavaScript error

### ISSUE THREAD

**Issue by CannibalVox** [vorple/vorple#8]
The following story has an issue:

"Test"

Include Vorple Multimedia by Juhana Leinonen.
Include Vorple by Juhana Leinonen.
Include Vorple Tooltips by Juhana Leinonen.
Include Vorple Hyperlinks by Juhana Leinonen.
Include Vorple Notifications by Juhana Leinonen.
Include Vorple Screen Effects by Juhana Leinonen.
Release along with the "Vorple" interpreter.

An Open Field is a room.  "Nearby is a small cave.  The muddy earth slopes downward toward a cliff to the south.  To the east, there is a forest, and beyond that, a massive castle.

Use the command 'win' to end the game."

Winning is an action applying to nothing. Understand "win" as winning.
After winning:
    say "Pausing..";
    pause the game.

When I run the win command in Chrome 40.0.2214.111 m, I receive a JavaScript error:   Uncaught TypeError: Cannot read property 'split' of undefined.

**Comment by sukima** [comment]
Any chance you could put this up on a site? It would be easier to debug with a live version I would gather.

**Comment by juhana** [comment]
Fixed in version 3.
