### ISSUE TITLE
Improve compatibility with IE or Chrome

### ISSUE THREAD

**Issue by hlabrand** [vorple/vorple#9]
The page http://vorple-if.com/doc/ notes that trying to open a Vorple game from the hard drive in IE makes the interpreter crash at the "Loading..." page.

I have encountered problems with Vorple I6 games who just refuse to open in Chrome much in the same way.

**Comment by hlabrand** [comment]
Opera seems to have the same problem too

**Comment by juhana** [comment]
Version 3 requires a local server, shouldn't be an issue anymore.
